---
gnome:
  autohide:
    setting: /org/gnome/shell/extensions/dash-to-dock/autohide true
  desktop_icons:
    setting: /org/gnome/desktop/background/show-desktop-icons true
  dock_position:
    setting: /org/gnome/shell/extensions/dash-to-dock/dock-position "'BOTTOM'"
  show_trash:
    setting: /org/gnome/shell/extensions/dash-to-dock/show-trash true
  preferred_monitor:
    setting: /org/gnome/shell/extensions/dash-to-dock/preferred-monitor 0
  custom_theme_shrink:
    setting: /org/gnome/shell/extensions/dash-to-dock/custom-theme-shrink true
  default_zoom_level:
    setting: /org/gnome/nautilus/icon-view/default-zoom-level "'small'"
  show_apps_button:
    setting: /org/gnome/shell/extensions/dash-to-dock/show-show-apps-button true
  button_layout: 
    setting: /org/gnome/desktop/wm/preferences/button-layout "'appmenu:minimize,maximize,close'"
  favorite_apps: 
    setting: >
      /org/gnome/shell/favorite-apps '[
        "slack_slack.desktop",
        "microsoft-edge.desktop",
        "chromium_chromium.desktop",
        "firefox_firefox.desktop",
        "code_code.desktop",
        "org.gnome.Terminal.desktop",
        "gnome-control-center.desktop"
      ]'
  keyboard_show_desktop:
    setting: /org/gnome/desktop/wm/keybindings/show-desktop '["<Primary><Super>d"]'
  system_sounds:
    setting: /org/gnome/desktop/sound/event-sounds false
  touchpad:
    setting: /org/gnome/desktop/peripherals/touchpad/tap-to-click true    
