---
tap:
    installed:
        - homebrew/bundle
        - homebrew/services
        - domt4/autoupdate

brew:
    installed:
        ## dockutil required
        - dockutil
        ## mas required for mac app store
        - mas 
        - awscli
        - ack
        - bash-completion
        - coreutils
        - cowsay
        - docker-compose
        - dos2unix 
        - fzf
        - go
        - graphviz
        - htop
        - hugo
        - imagemagick
        - jq
        - lua
        - maven
        - ngrep
        - nmap
        - node
        - openvpn-connect
        - pinentry-mac
        - pyenv-virtualenv
        - readline
        - ripgrep
        - ruby
        - rust
        - sleepwatcher
        ## socat required for gui
        - socat
        - ssh-copy-id
        - the_silver_searcher
        - tcl-tk
        - tmux
        - unar
        - watchman
        - wget
        - yq
        - zsh
brew_cask:
    installed:
        - antigravity
        - 1password
        - amethyst
        - canva
        - chatgpt
        - cleanmymac
        - docker
        - duet
        - firefox
        - freecad
        - godot
        - google-chrome
        - google-drive
        - iterm2
        - keka
        - kensingtonworks
        - logitech-options
        - macvim
        - raspberry-pi-imager
        - slack
        - steam
        - surfshark
        - synology-image-assistant
        - visual-studio-code
        - ultimaker-cura
        ## xquartz required for gui
        - xquartz
        - zoom
        
